#!/usr/bin/env python3

import irqclient
import argparse
import sys

def get_irq_client(host, port):
    api = irqclient.IrqServiceApi(host, port)
    client = irqclient.IrqClient(api)
    return client


def main():
    parser = argparse.ArgumentParser()

    parser.add_argument('--host',
        required=True,
        metavar='host',
        type=str,
        nargs='?',
        default='localhost',
        help='host of API web service')
    parser.add_argument('--port',
        required=True,
        metavar='port',
        type=str,
        nargs='?',
        default='5000',
        help='port of API web service')

    subparsers = parser.add_subparsers(title='commands')

    show_totals_parser = subparsers.add_parser('show_totals')
    show_totals_parser.set_defaults(action='show_totals')

    show_interrupts_parser = subparsers.add_parser('show_interrupts')
    show_interrupts_parser.set_defaults(action='show_interrupts')

    show_cpu_affinity_parser = subparsers.add_parser('show_cpu_affinity')
    show_cpu_affinity_parser.set_defaults(action='show_cpu_affinity')
    show_cpu_affinity_parser.add_argument('--irq',
        required=True,
        metavar='irq',
        type=str,
        help='IRQ for which to get current CPU affinity')

    args = parser.parse_args()
    action = args.action

    client = get_irq_client(args.host, args.port)
    print_helper = irqclient.PrintHelper(sys.stdout)

    if action == 'show_totals':
        print_helper.print_interrupt_totals(client.get_interrupt_totals())
    elif action == 'show_interrupts':
        print_helper.print_interrupts(client.get_interrupts())
    elif action == 'show_cpu_affinity':
        print_helper.print_cpu_affinity(client.get_irq_cpu_affinity(args.irq))

if __name__ == "__main__":
  main()
