#!/usr/bin/env python3

import irqclient
import sys

def get_irq_client(host, port):
    api = irqclient.IrqServiceApi(host, port)
    client = irqclient.IrqClient(api)
    return client


def main():
    service_host = sys.argv[1]
    service_port = sys.argv[2]
    client = get_irq_client(service_host, service_port)
    client.get_interrupt_totals()

if __name__ == "__main__":
  main()
